### ISSUE TITLE
Type Error for Venusaur in Out[19]:

### ISSUE THREAD

**Issue by heidobito** [snazrul1/PyRevolution#1]
In [19]:

new_df.head()

Out[19]:
    #   Attack  Defense     HP  Name    Sp. Atk     Sp. Def     Speed   Total   Type
0   001     49  49  45  Bulbasaur   65  65  45  318     Grass
1   001     49  49  45  Bulbasaur   65  65  45  318     Poison
2   002     62  63  60  Ivysaur     80  80  60  405     Grass
3   002     62  63  60  Ivysaur     80  80  60  405     Poison
4   003     82  83  80  Venusaur    100     100     80  525     Water

It displays Water type for Venusaur, however the original database shows Grass and Poison.  Not sure what happened in step 19, but "new_df" is not accurate.

I'm enjoying this but would like to find a fix before I continue with the rest of the code.

Any help will be appreciated!
Thanks!!

**Comment by mas-dse-ssnazrul** [comment]
Thanks for the catch! I believe the source of the error is during the creation of the newDict dictionary that was used to create the new_df dataframe. Hence we need to debug this:

#Creating new Data Frame where the Type values are separated from the list
newDict={}
stats_col=["#","Name","Total","HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]

#Collecting the list of Type for each Pokemon
Dict['Type']=df['Type'].values

#Creating an empty list for each key (column)
for col in stats_col:
    newDict[col]=[]
    newDict['Type']=[]

#Populating each the dictionary value (empty list) with data 
for row in range(len(Dict['#'])):
    for t in Dict['Type'][row]:
        for col in stats_col:
            #Append all columns except Type to the new dictionary
            newDict[col].append(Dict[col][row])
        #Appending the Type separately for each Pokemon  in the new dictionary
        newDict['Type'].append(t)
        
#Convert dictionary to a Data Frame
new_df = pd.DataFrame(newDict)

**Comment by snazrul1** [comment]
Thanks for the catch! I believe the source of the error is during the creation of the newDict dictionary that was used to create the new_df dataframe. Hence we need to debug this:

#Creating new Data Frame where the Type values are separated from the list
newDict={}
stats_col=["#","Name","Total","HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]

#Collecting the list of Type for each Pokemon
Dict['Type']=df['Type'].values

#Creating an empty list for each key (column)
for col in stats_col:
newDict[col]=[]
newDict['Type']=[]

#Populating each the dictionary value (empty list) with data 
for row in range(len(Dict['#'])):
for t in Dict['Type'][row]:
for col in stats_col:
#Append all columns except Type to the new dictionary
newDict[col].append(Dict[col][row])
#Appending the Type separately for each Pokemon in the new dictionary
newDict['Type'].append(t)

#Convert dictionary to a Data Frame
new_df = pd.DataFrame(newDict)

**Comment by heidobito** [comment]
Thanks for the reply, I'm learning Python and enjoy Pokemon so this has
been wonderful!!!  I'll see what I can learn from this...please keep me
posted.  Thanks again!  Wonderful.
